// src/components/CustomCursor.jsx
import { useEffect, useRef, useState } from "react";
import { createPortal } from "react-dom";
import { subscribe } from "@/lib/physics/scheduler";
import { pointer, startPointerEngine } from "@/lib/physics/pointer";
import { MATERIAL, CURSOR, SLEEP } from "@/lib/physics/tokens";
import { integrateSpring, clamp, tanhSat, angleDelta } from "@/lib/physics/math";

/**
 * The cursor is simulated as a small swimming organism.
 *
 *   CORE  — the dot. A critically damped spring on the predicted pointer
 *           target: exact, never overshoots, defines "where you are".
 *   BODY  — the ring. A soft viscous membrane coupled to the core, integrated
 *           in the travel frame so it is loose along its path and tight across
 *           it, and deformed by an area-preserving matrix (det = 1) so it
 *           stretches without ever gaining or losing visual mass.
 *
 * Everything integrates on the shared fixed-timestep scheduler, so behaviour is
 * identical at 60Hz and 240Hz, and the whole system sleeps when it settles.
 */
export default function CustomCursor() {
  const dotRef = useRef(null);
  const ringRef = useRef(null);
  const [enabled, setEnabled] = useState(false);

  useEffect(() => {
    const fine = window.matchMedia("(hover: hover) and (pointer: fine)").matches;
    const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (!fine || reduced) return;
    setEnabled(true);
    document.body.classList.add("cursor-ready");

    const stopPointer = startPointerEngine();

    const cx = window.innerWidth / 2;
    const cy = window.innerHeight / 2;

    // ── state ─────────────────────────────────────────────────────────
    const coreX = { x: cx, v: 0 }, coreY = { x: cy, v: 0 };
    const bodyX = { x: cx, v: 0 }, bodyY = { x: cy, v: 0 };
    const shear = { x: 0, v: 0 };
    const glow = { x: 0, v: 0 };            // label opacity
    const swim = { x: 0, v: 0 };            // 0..1 travel effort

    let theta = 0;     // deformation orientation (deg)
    let visible = false;
    let lastLabel = "";
    let prevCoreX = cx, prevCoreY = cy, prevBodyX = cx, prevBodyY = cy;
    let prevShear = 0, prevTheta = 0, prevGlow = 0;
    let lastHover = false, lastIsLabel = false, lastDotOpacity = "", lastRingOpacity = "", lastColor = "";

    // scratch — the hot loop allocates nothing
    const f = { tx: 1, ty: 0, nx: 0, ny: 1 };
    const st = { x: 0, v: 0 }, sn = { x: 0, v: 0 };

    const step = (dt) => {
      if (!pointer.seen) return;

      if (!visible) {
        visible = true;
        coreX.x = bodyX.x = prevCoreX = prevBodyX = pointer.x;
        coreY.x = bodyY.x = prevCoreY = prevBodyY = pointer.y;
      }

      // Retain only the previous simulation pose; render interpolation makes the
      // 120 Hz physics visually continuous on 144/165/240 Hz displays.
      prevCoreX = coreX.x; prevCoreY = coreY.x;
      prevBodyX = bodyX.x; prevBodyY = bodyY.x;
      prevShear = shear.x; prevTheta = theta; prevGlow = glow.x;

      // ── CORE ────────────────────────────────────────────────────────
      const P = MATERIAL.precision;
      integrateSpring(coreX, pointer.tx, P.omega, P.zeta, dt);
      integrateSpring(coreY, pointer.ty, P.omega, P.zeta, dt);

      // travel frame (tangent / normal)
      const s = pointer.speed;
      // only trust the travel direction once the movement is clearly intentional —
      // below that, a sensitive mouse's noise flips the frame and shakes the ring
      if (s > 90) { f.tx = pointer.vx / s; f.ty = pointer.vy / s; }
      f.nx = -f.ty; f.ny = f.tx;

      // ── BODY: anisotropic viscous spring coupled to the core ────────
      const G = MATERIAL.glass;
      const ex = bodyX.x - coreX.x, ey = bodyY.x - coreY.x;
      st.x = ex * f.tx + ey * f.ty;
      sn.x = ex * f.nx + ey * f.ny;
      st.v = bodyX.v * f.tx + bodyY.v * f.ty;
      sn.v = bodyX.v * f.nx + bodyY.v * f.ny;

      integrateSpring(st, 0, G.omega * CURSOR.tangentScale, G.zeta, dt);
      integrateSpring(sn, 0, G.omega * CURSOR.normalScale, G.zeta, dt);

      bodyX.x = coreX.x + st.x * f.tx + sn.x * f.nx;
      bodyY.x = coreY.x + st.x * f.ty + sn.x * f.ny;
      bodyX.v = st.v * f.tx + sn.v * f.nx;
      bodyY.v = st.v * f.ty + sn.v * f.ny;

      // the core must stay enclosed by the body
      const ox = bodyX.x - coreX.x, oy = bodyY.x - coreY.x;
      const lag = Math.hypot(ox, oy);
      if (lag > CURSOR.maxLag) {
        const k = CURSOR.maxLag / lag;
        bodyX.x = coreX.x + ox * k;
        bodyY.x = coreY.x + oy * k;
      }

      // ── deformation: speed + lag, saturated, then softly sprung ─────
      const effort = tanhSat(CURSOR.shearAlpha * s + lag / 46);
      integrateSpring(swim, effort, 5.5, 1.0, dt);
      // drive deformation from the smoothed effort, never the raw sample
      integrateSpring(shear, pointer.label ? 0 : CURSOR.shearMax * swim.x, 7, 1.0, dt);
      integrateSpring(glow, pointer.label ? 1 : 0, 22, 1.0, dt);

      if (s > 140) {
        const want = (Math.atan2(pointer.vy, pointer.vx) * 180) / Math.PI;
        theta += angleDelta(want, theta) * clamp(dt * 7, 0, 1);
      }
    };

    const render = (alpha = 1) => {
      if (!visible) return;
      const d = dotRef.current, r = ringRef.current;
      const a = clamp(alpha, 0, 1);
      const ix = prevCoreX + (coreX.x - prevCoreX) * a;
      const iy = prevCoreY + (coreY.x - prevCoreY) * a;
      const bx = prevBodyX + (bodyX.x - prevBodyX) * a;
      const by = prevBodyY + (bodyY.x - prevBodyY) * a;
      const sh = prevShear + (shear.x - prevShear) * a;
      const th = prevTheta + angleDelta(theta, prevTheta) * a;
      const gl = prevGlow + (glow.x - prevGlow) * a;

      if (d) {
        const opacity = pointer.inside ? "1" : "0";
        if (opacity !== lastDotOpacity) { d.style.opacity = opacity; lastDotOpacity = opacity; }
        d.style.transform = `translate3d(${ix.toFixed(2)}px, ${iy.toFixed(2)}px, 0) translate(-50%,-50%)`;
      }

      if (r) {
        // R(θ)·diag(eˢ, e⁻ˢ)·R(−θ) — determinant 1, so area is preserved
        const rad = (th * Math.PI) / 180;
        const c = Math.cos(rad), sn2 = Math.sin(rad);
        const ep = Math.exp(sh), em = Math.exp(-sh);
        const m11 = ep * c * c + em * sn2 * sn2;
        const m12 = (ep - em) * c * sn2;
        const m22 = ep * sn2 * sn2 + em * c * c;
        r.style.transform = `translate3d(${bx.toFixed(2)}px, ${by.toFixed(2)}px, 0) translate(-50%,-50%) matrix(${m11.toFixed(4)}, ${m12.toFixed(4)}, ${m12.toFixed(4)}, ${m22.toFixed(4)}, 0, 0)`;
        const hover = !!pointer.target && !pointer.label;
        const isLabel = !!pointer.label;
        if (hover !== lastHover) { r.classList.toggle("is-hover", hover); lastHover = hover; }
        if (isLabel !== lastIsLabel) { r.classList.toggle("is-label", isLabel); lastIsLabel = isLabel; }
        const opacity = pointer.down ? "0.5" : pointer.inside ? "1" : "0";
        if (opacity !== lastRingOpacity) { r.style.opacity = opacity; lastRingOpacity = opacity; }

        const text = pointer.label || lastLabel;
        if (r.textContent !== text) r.textContent = text;
        if (pointer.label) lastLabel = pointer.label;
        const color = `rgba(255,255,255,${gl.toFixed(3)})`;
        if (color !== lastColor) { r.style.color = color; lastColor = color; }
      }
    };

    const settled = () => {
      if (!visible) return true;
      const err = Math.hypot(bodyX.x - pointer.tx, bodyY.x - pointer.ty);
      const vel = Math.hypot(bodyX.v, bodyY.v) + Math.hypot(coreX.v, coreY.v);
      return (
        err < SLEEP.pos &&
        vel < SLEEP.vel &&
        swim.x < 0.01 &&
        Math.abs(shear.x) < 0.004 &&
        Math.abs(glow.v) < 0.01
      );
    };

    const unsubscribe = subscribe({ step, render, settled });
    return () => {
      unsubscribe();
      stopPointer();
      document.body.classList.remove("cursor-ready");
    };
  }, []);

  if (!enabled) return null;
  return createPortal(
    <>
      <div ref={dotRef} className="cursor-dot" style={{ opacity: 0 }} aria-hidden />
      <div ref={ringRef} className="cursor-ring" style={{ opacity: 0 }} aria-hidden />
    </>,
    document.body
  );
}

// solid/components/CustomCursor.jsx
import { createSignal, createEffect, onMount, onCleanup, Show } from "solid-js";
import { Portal } from "solid-js/web";
import { subscribe } from "@/lib/physics/scheduler";
import { pointer, startPointerEngine } from "@/lib/physics/pointer";
import { MATERIAL, CURSOR, SLEEP } from "@/lib/physics/tokens";
import { integrateSpring, clamp, tanhSat, angleDelta } from "@/lib/physics/math";
import { lowPowerMode, PERFORMANCE_TIER_EVENT } from "@/lib/performance-tier";
import { customCursorEnabled, CURSOR_EVENT } from "@/lib/cursor-preference";

/**
 * CustomCursor — Solid port of src/components/CustomCursor.jsx.
 *
 * The cursor preserves the browser pointer's OS-processed movement while its
 * outline behaves like a small swimming organism.
 *
 *   POSITION — the core dot reads PointerEvent clientX/clientY through a tiny
 *              spatial deadband that absorbs ±1 px OS noise. Movement beyond
 *              it snaps to the browser coordinate, so there is no timed easing,
 *              accumulating lag, sensitivity change, prediction, or DPR math.
 *              The outer ring follows that stabilized CSS-pixel target through
 *              a capped spring, so the dot can escape it during a quick gesture.
 *   MATERIAL — bounded underdamped springs shape and recapture the ring like a
 *              soft membrane, producing a gentle rebound before settling.
 *
 * Deformation integrates on the shared fixed-timestep scheduler, so behaviour
 * is identical at 60Hz and 240Hz and the system sleeps when it settles.
 *
 * ── What the Solid port changes ──────────────────────────────────────────
 * Nothing about the physics. The React version already kept every hot value
 * in refs and wrote transforms directly, precisely to avoid a re-render per
 * frame. Solid makes that the natural shape rather than an optimisation:
 * locals are stable because the body runs once, so the refs simply become
 * `let`, and the simulation is exactly as it was.
 */
export default function CustomCursor() {
  let dotEl;
  let ringEl;

  const [enabled, setEnabled] = createSignal(false);
  const [lowPower, setLowPower] = createSignal(lowPowerMode());
  const [preferenceEnabled, setPreferenceEnabled] = createSignal(customCursorEnabled());

  onMount(() => {
    const updateTier = (event) => setLowPower(event.detail);
    const updatePreference = (event) => setPreferenceEnabled(Boolean(event.detail));
    window.addEventListener(PERFORMANCE_TIER_EVENT, updateTier);
    window.addEventListener(CURSOR_EVENT, updatePreference);
    onCleanup(() => {
      window.removeEventListener(PERFORMANCE_TIER_EVENT, updateTier);
      window.removeEventListener(CURSOR_EVENT, updatePreference);
    });
  });

  createEffect(() => {
    const prefOn = preferenceEnabled();
    const isLowPower = lowPower();

    setEnabled(false);
    const fine = window.matchMedia("(hover: hover) and (pointer: fine)").matches;
    const reduced = window.matchMedia("(prefers-reduced-motion: reduce)").matches;
    if (!prefOn || !fine || reduced || isLowPower) {
      document.body.classList.remove("cursor-ready");
      return;
    }

    setEnabled(true);
    document.body.classList.add("cursor-ready");

    const stopPointer = startPointerEngine();

    // ── state ─────────────────────────────────────────────────────────
    const ringX = { x: 0, v: 0 };           // spring-follow centre
    const ringY = { x: 0, v: 0 };
    const shear = { x: 0, v: 0 };
    const scale = { x: 1, v: 0 };           // press + travel expansion
    const glow = { x: 0, v: 0 };            // label opacity
    const swim = { x: 0, v: 0 };            // 0..1 travel effort

    let theta = 0;     // deformation orientation (deg)
    let visible = false;
    let dotReady = false, dotMoved = false;
    let dotX = 0, dotY = 0;
    let lastLabel = "";
    let prevRingX = 0, prevRingY = 0;
    let prevShear = 0, prevScale = 1, prevTheta = 0, prevGlow = 0;
    let lastHover = false, lastIsLabel = false, lastDotOpacity = "", lastRingOpacity = "", lastColor = "";

    // Spatial hysteresis, not temporal smoothing: ignore only motion contained
    // within the noise radius, then snap fully to the browser coordinate.
    const sampleDot = () => {
      dotMoved = false;
      if (!pointer.seen) return;
      if (!dotReady) {
        dotX = pointer.rawX;
        dotY = pointer.rawY;
        dotReady = true;
        dotMoved = true;
        return;
      }
      const dx = pointer.rawX - dotX;
      const dy = pointer.rawY - dotY;
      if (Math.hypot(dx, dy) <= CURSOR.dotJitterDeadband) return;
      dotX = pointer.rawX;
      dotY = pointer.rawY;
      dotMoved = true;
    };

    const step = (dt) => {
      if (!pointer.seen) return;

      if (!visible) {
        visible = true;
        ringX.x = prevRingX = dotX;
        ringY.x = prevRingY = dotY;
      }

      // The dot is never interpolated. Only the ring's bounded follower and
      // material response use the fixed-timestep spring simulation.
      prevRingX = ringX.x; prevRingY = ringY.x;
      prevShear = shear.x; prevScale = scale.x; prevTheta = theta; prevGlow = glow.x;

      // A velocity estimate belongs to the last input sample. Release it after
      // a brief grace period so deformation cannot loop forever while idle.
      const idleFor = performance.now() / 1000 - pointer.movedAt;
      const s = dotMoved && idleFor <= CURSOR.idleReleaseDelay ? pointer.speed : 0;

      integrateSpring(ringX, dotX, MATERIAL.follow.omega, MATERIAL.follow.zeta, dt);
      integrateSpring(ringY, dotY, MATERIAL.follow.omega, MATERIAL.follow.zeta, dt);

      let tetherX = dotX - ringX.x;
      let tetherY = dotY - ringY.x;
      let tetherDistance = Math.hypot(tetherX, tetherY);
      if (tetherDistance > CURSOR.ringMaxLag) {
        const nx = tetherX / tetherDistance;
        const ny = tetherY / tetherDistance;
        ringX.x = dotX - nx * CURSOR.ringMaxLag;
        ringY.x = dotY - ny * CURSOR.ringMaxLag;
        // Remove only velocity that would stretch the tether farther. Inward
        // velocity survives, so the ring catches the dot without a hard snap.
        const inwardVelocity = ringX.v * nx + ringY.v * ny;
        if (inwardVelocity < 0) {
          ringX.v -= inwardVelocity * nx;
          ringY.v -= inwardVelocity * ny;
        }
        tetherX = nx * CURSOR.ringMaxLag;
        tetherY = ny * CURSOR.ringMaxLag;
        tetherDistance = CURSOR.ringMaxLag;
      }

      const movementEffort = tanhSat(CURSOR.shearAlpha * s);
      const tetherEffort = clamp(tetherDistance / CURSOR.ringMaxLag, 0, 1);
      const effort = Math.max(movementEffort, tetherEffort);
      integrateSpring(swim, effort, MATERIAL.flow.omega, MATERIAL.flow.zeta, dt);
      integrateSpring(
        shear,
        pointer.label ? 0 : CURSOR.shearMax * swim.x,
        MATERIAL.liquid.omega,
        MATERIAL.liquid.zeta,
        dt,
      );
      const scaleTarget = pointer.down ? CURSOR.pressScale : 1 + CURSOR.motionExpansion * swim.x;
      integrateSpring(scale, scaleTarget, MATERIAL.bounce.omega, MATERIAL.bounce.zeta, dt);
      integrateSpring(glow, pointer.label ? 1 : 0, MATERIAL.glass.omega, MATERIAL.glass.zeta, dt);

      if (tetherDistance > 0.75) {
        const want = (Math.atan2(tetherY, tetherX) * 180) / Math.PI;
        theta += angleDelta(want, theta) * clamp(dt * 10, 0, 1);
      }
    };

    const render = (alpha = 1) => {
      if (!visible) return;
      const d = dotEl, r = ringEl;
      const a = clamp(alpha, 0, 1);
      const px = dotX;
      const py = dotY;
      const rx = prevRingX + (ringX.x - prevRingX) * a;
      const ry = prevRingY + (ringY.x - prevRingY) * a;
      const sh = prevShear + (shear.x - prevShear) * a;
      const sc = prevScale + (scale.x - prevScale) * a;
      const th = prevTheta + angleDelta(theta, prevTheta) * a;
      const gl = prevGlow + (glow.x - prevGlow) * a;

      if (d) {
        const opacity = pointer.inside ? "1" : "0";
        if (opacity !== lastDotOpacity) { d.style.opacity = opacity; lastDotOpacity = opacity; }
        d.style.transform = `translate3d(${px.toFixed(2)}px, ${py.toFixed(2)}px, 0) translate(-50%,-50%)`;
      }

      if (r) {
        // Uniform bounce multiplies the area-preserving directional membrane.
        // Only this outer ring uses spring-follow translation; the dot remains raw.
        const rad = (th * Math.PI) / 180;
        const c = Math.cos(rad), sn2 = Math.sin(rad);
        const ep = sc * Math.exp(sh), em = sc * Math.exp(-sh);
        const m11 = ep * c * c + em * sn2 * sn2;
        const m12 = (ep - em) * c * sn2;
        const m22 = ep * sn2 * sn2 + em * c * c;
        r.style.transform = `translate3d(${rx.toFixed(2)}px, ${ry.toFixed(2)}px, 0) translate(-50%,-50%) matrix(${m11.toFixed(4)}, ${m12.toFixed(4)}, ${m12.toFixed(4)}, ${m22.toFixed(4)}, 0, 0)`;

        const hover = !!pointer.target && !pointer.label;
        const isLabel = !!pointer.label;
        if (hover !== lastHover) { r.classList.toggle("is-hover", hover); lastHover = hover; }
        if (isLabel !== lastIsLabel) { r.classList.toggle("is-label", isLabel); lastIsLabel = isLabel; }
        const opacity = pointer.down ? "0.5" : pointer.inside ? "1" : "0";
        if (opacity !== lastRingOpacity) { r.style.opacity = opacity; lastRingOpacity = opacity; }

        const text = pointer.label || lastLabel;
        if (r.textContent !== text) r.textContent = text;
        if (pointer.label) lastLabel = pointer.label;
        const color = `rgba(255,255,255,${gl.toFixed(3)})`;
        if (color !== lastColor) { r.style.color = color; lastColor = color; }
      }
    };

    const settled = () => {
      if (!visible) return true;
      return (
        Math.hypot(ringX.x - dotX, ringY.x - dotY) < SLEEP.pos &&
        Math.hypot(ringX.v, ringY.v) < SLEEP.vel &&
        swim.x < 0.01 &&
        Math.abs(swim.v) < 0.01 &&
        Math.abs(shear.x) < 0.004 &&
        Math.abs(shear.v) < 0.01 &&
        Math.abs(scale.x - (pointer.down ? CURSOR.pressScale : 1)) < 0.002 &&
        Math.abs(scale.v) < 0.01 &&
        Math.abs(glow.v) < 0.01
      );
    };

    const unsubscribe = subscribe({ sample: sampleDot, step, render, settled });

    onCleanup(() => {
      unsubscribe();
      stopPointer();
      document.body.classList.remove("cursor-ready");
    });
  });

  return (
    <Show when={enabled()}>
      <Portal>
        <div ref={dotEl} class="cursor-dot" style={{ opacity: 0 }} aria-hidden />
        <div ref={ringEl} class="cursor-ring" style={{ opacity: 0 }} aria-hidden />
      </Portal>
    </Show>
  );
}
