// src/pages/Splash.jsx
import React, { useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { motion, useMotionValue, useSpring, useTransform } from "framer-motion";
import { ArrowUpRight, Plus, ArrowDown } from "lucide-react";
import { useAuth } from "@/lib/AuthContext";
import MagneticButton from "@/components/MagneticButton";
import Marquee from "@/components/Marquee";
import KineticBackground from "@/components/KineticBackground";

const LOGO = "https://media.base44.com/images/public/6a2fcc3f4fec7200fed7a889/b6064da4f_MabisLogo-800x800.png";

const EASE = [0.16, 1, 0.3, 1];
const charParent = (stagger, delay) => ({ hidden: {}, show: { transition: { staggerChildren: stagger, delayChildren: delay } } });
const charChild = {
  hidden: { y: "115%", opacity: 0 },
  show: { y: "0%", opacity: 1, transition: { duration: 0.7, ease: EASE } },
};

function SplitChars({ text, stagger = 0.05, delay = 0, className = "" }) {
  return (
    <motion.span
      className={`reveal-mask ${className}`}
      variants={charParent(stagger, delay)}
      initial="hidden"
      animate="show"
      style={{ display: "inline-block" }}
    >
      {Array.from(text).map((c, i) => (
        <span key={i} style={{ display: "inline-block", overflow: "hidden", verticalAlign: "top" }}>
          <motion.span variants={charChild} style={{ display: "inline-block" }}>{c === " " ? "\u00A0" : c}</motion.span>
        </span>
      ))}
    </motion.span>
  );
}

export default function Splash() {
  const navigate = useNavigate();
  const { isAuthenticated } = useAuth();

  // pointer parallax for the hero typography
  const mx = useMotionValue(0);
  const my = useMotionValue(0);
  const sx = useSpring(mx, { stiffness: 50, damping: 20 });
  const sy = useSpring(my, { stiffness: 50, damping: 20 });
  const titleX = useTransform(sx, (v) => v * 24);
  const titleY = useTransform(sy, (v) => v * 14);
  const bgX = useTransform(sx, (v) => v * -28);
  const bgY = useTransform(sy, (v) => v * -18);

  useEffect(() => {
    const fine = window.matchMedia("(hover: hover) and (pointer: fine)").matches;
    if (!fine) return;
    const onMove = (e) => {
      mx.set((e.clientX / window.innerWidth - 0.5) * 2);
      my.set((e.clientY / window.innerHeight - 0.5) * 2);
    };
    window.addEventListener("mousemove", onMove);
    return () => window.removeEventListener("mousemove", onMove);
  }, [mx, my]);

  const enter = () => navigate(isAuthenticated ? "/home" : "/login");

  return (
    <div className="relative min-h-screen w-full overflow-hidden bg-ink text-bone">
      <motion.div style={{ x: bgX, y: bgY }} className="absolute inset-0">
        <KineticBackground variant="ink" />
      </motion.div>

      {/* top bar */}
      <motion.div
        initial={{ y: -20, opacity: 0 }}
        animate={{ y: 0, opacity: 1 }}
        transition={{ delay: 0.2, duration: 0.6, ease: EASE }}
        className="absolute left-0 right-0 top-0 z-30 flex items-center justify-between px-4 py-4 sm:px-8 sm:py-5"
      >
        <div className="flex items-center gap-3">
          <span className="flex h-8 w-8 items-center justify-center border border-bone/30">
            <img src={LOGO} alt="MABIS" className="h-5 w-5 object-contain" />
          </span>
          <span className="tech-label text-bone/60"><span className="sm:hidden">MABIS</span><span className="hidden sm:inline">MABIS COMMUNITY MEETING</span></span>
        </div>
        <span className="tech-label hidden sm:block text-bone/50">EST. BANGKOK TH</span>
      </motion.div>

      {/* vertical side labels */}
      <motion.span
        initial={{ opacity: 0, y: 20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 1, duration: 0.8, ease: EASE }}
        className="vert-text tech-label absolute left-5 sm:left-8 top-1/2 -translate-y-1/2 text-bone/45 z-20 hidden md:block"
      >SECONDARY COMMUNITY</motion.span>
      <motion.span
        initial={{ opacity: 0, y: -20 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 1.1, duration: 0.8, ease: EASE }}
        className="vert-text tech-label absolute right-5 sm:right-8 top-1/2 -translate-y-1/2 text-bone/45 z-20 hidden md:block"
      >N° 2026 EDITION</motion.span>

      {/* crosshair decorations */}
      <motion.div initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.6 }} className="pointer-events-none absolute inset-5 sm:inset-8 corner-bracket z-20" />
      <Plus className="absolute top-1/3 right-1/4 h-2.5 w-2.5 text-primary/60 z-20" />

      {/* center stage with pointer parallax */}
      <div className="relative z-10 flex min-h-[100dvh] flex-col items-start justify-center px-4 pb-20 pt-20 sm:min-h-screen sm:items-center sm:px-8 sm:pb-0 sm:pt-0">
        {/* giant cropped background word */}
        <motion.span
          initial={{ opacity: 0 }} animate={{ opacity: 0.05 }} transition={{ delay: 0.4, duration: 1.2 }}
          className="pointer-events-none absolute top-[14%] left-1/2 -translate-x-1/2 font-display font-thin tracking-ultra text-bone leading-none select-none whitespace-nowrap huge-crop"
        >
          MABIS
        </motion.span>

        <motion.div
          initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.5, duration: 0.6 }}
          className="mb-4 flex max-w-full items-center gap-3 tech-label text-primary sm:mb-6"
        >
          <motion.span initial={{ scaleX: 0 }} animate={{ scaleX: 1 }} transition={{ delay: 0.55, duration: 0.6, ease: EASE }} className="block h-px w-8 bg-primary origin-left" /> 01 — SECONDARY COMMUNITY MEETING APP
        </motion.div>

        <motion.div style={{ x: titleX, y: titleY }} className="will-change-transform">
          <h1 className="text-left font-display text-[clamp(2.8rem,14vw,4.1rem)] font-extralight leading-[0.88] tracking-ultra sm:text-center sm:text-8xl md:text-9xl lg:text-[11rem]">
            <span className="block">
              <SplitChars text="COMMUNITY" stagger={0.05} delay={0.6} />
            </span>
            <span className="block mt-2 sm:mt-3 text-stroke-bone">
              <SplitChars text="MEETING" stagger={0.05} delay={1.0} />
            </span>
          </h1>
        </motion.div>

        <motion.div
          initial={{ scaleX: 0 }} animate={{ scaleX: 1 }} transition={{ delay: 1.6, duration: 0.8, ease: EASE }}
          className="my-6 h-px w-32 origin-left bg-bone/40 sm:my-10 sm:w-40 sm:origin-center"
        />

        <motion.p
          initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 1.7, duration: 0.7 }}
          className="max-w-md text-left sm:text-center text-sm sm:text-base text-bone/65 leading-relaxed"
        >
          A weekly ritual of voice, presence, and shared decision —
          recorded, remembered, and refined by the secondary community.
        </motion.p>

        <div className="mt-7 w-full sm:mt-12 sm:w-auto">
          <MagneticButton strength={0.4}>
            <button
              onClick={enter}
              data-cursor="ENTER"
              className="liquid-btn liquid-ink group relative flex w-full items-center justify-between gap-3 border border-bone/40 bg-bone/5 px-5 py-4 text-bone backdrop-blur-sm sm:w-auto sm:justify-start sm:gap-4 sm:px-8"
            >
              <span className="tech-label">N° 02</span>
              <span className="text-lg sm:text-xl font-display font-normal tracking-tight">
                {isAuthenticated ? "ENTER START" : "ENTER LOG IN"}
              </span>
              <span className="relative flex h-8 w-8 items-center justify-center overflow-hidden">
                <ArrowUpRight className="h-6 w-6" />
              </span>
            </button>
          </MagneticButton>
        </div>

        {/* scroll cue */}
        <motion.div
          initial={{ opacity: 0 }} animate={{ opacity: 1 }} transition={{ delay: 0.4, duration: 0.6 }}
          className="absolute bottom-16 right-5 hidden flex-col items-center gap-2 sm:right-10 sm:flex"
        >
          <span className="tech-label vert-text text-bone/45">SCROLL</span>
          <motion.span
            animate={{ y: [0, 8, 0] }}
            transition={{ duration: 1.6, repeat: Infinity, ease: "easeInOut" }}
          >
            <ArrowDown className="h-4 w-4 text-bone/50" />
          </motion.span>
        </motion.div>
      </div>

      {/* bottom marquee */}
      <div className="absolute bottom-0 left-0 right-0 z-10 border-t border-bone/15 py-3 bg-ink/80 backdrop-blur-sm">
        <Marquee speed={32} className="text-bone/55">
          {Array.from({ length: 6 }).map((_, i) => (
            <span key={i} className="flex items-center tech-label">
              <span className="px-6">SECONDARY COMMUNITY MEETING</span>
              <Plus className="h-3 w-3 text-primary/70" />
              <span className="px-6">FRIDAY WEEKLY</span>
              <Plus className="h-3 w-3 text-primary/70" />
              <span className="px-6">MABIS BANGKOK</span>
              <Plus className="h-3 w-3 text-primary/70" />
            </span>
          ))}
        </Marquee>
      </div>
    </div>
  );
}

// solid/pages/Splash.jsx
import { createSignal, onMount, onCleanup, For } from "solid-js";
import { ArrowUpRight, Plus, ArrowDown } from "lucide-solid";
import { subscribe } from "@/lib/physics/scheduler";
import { integrateSpring } from "@/lib/physics/math";
import { springFromFramer, finePointer } from "~/lib/motion";
import {
  JapaneseText,
  KineticBackground,
  Marquee,
  MagneticButton,
  SplitChars,
} from "~/components/primitives";

const LOGO = "https://media.base44.com/images/public/6a2fcc3f4fec7200fed7a889/b6064da4f_MabisLogo-800x800.png/v1/fill/w_144,h_144/logo.webp";
const EASE_CSS = "cubic-bezier(0.16, 1, 0.3, 1)";

/**
 * Splash — SolidJS port of src/pages/Splash.jsx.
 *
 * Every class name, delay, duration and easing curve is carried over
 * unchanged; the markup is identical apart from className→class. What changed
 * is only HOW the motion is driven:
 *
 *   framer <motion.x initial/animate/transition>  →  CSS transition + a single
 *       mount signal, with the original delay/duration/ease preserved.
 *   framer useSpring/useTransform parallax        →  the app's own analytic
 *       spring on the shared physics scheduler (see lib/motion.js for the
 *       stiffness/damping → ω/ζ conversion).
 *
 * Net effect: the same animation, run by the compositor rather than a JS
 * animation library, and the scheduler sleeps once motion settles.
 */

/** One-shot entrance: mirrors framer's initial → animate with a delay. */
function Enter(props) {
  const [shown, setShown] = createSignal(false);
  onMount(() => {
    requestAnimationFrame(() => requestAnimationFrame(() => setShown(true)));
  });

  const style = () => {
    const d = props.duration ?? 0.6;
    const delay = props.delay ?? 0;
    const ease = props.ease ?? EASE_CSS;
    return {
      opacity: shown() ? (props.toOpacity ?? 1) : (props.fromOpacity ?? 0),
      transform: shown()
        ? "translate3d(0,0,0) scaleX(1)"
        : `translate3d(${props.fromX ?? 0}px, ${props.fromY ?? 0}px, 0) scaleX(${props.fromScaleX ?? 1})`,
      transition: `opacity ${d}s ${ease} ${delay}s, transform ${d}s ${ease} ${delay}s`,
      ...(props.extraStyle || {}),
    };
  };

  return <div class={props.class} style={style()}>{props.children}</div>;
}

export default function Splash() {
  let bgRef;
  let titleRef;

  // The React page reads auth to pick the button label. AuthContext has not
  // been ported yet — that is its own migration task — so this slice renders
  // the signed-out label. Everything visual is unaffected.
  const isAuthenticated = () => false;

  onMount(() => {
    if (!finePointer()) return;

    const { omega, zeta } = springFromFramer(50, 20, 1);
    const sx = { x: 0, v: 0 };
    const sy = { x: 0, v: 0 };
    let tx = 0;
    let ty = 0;

    const onMove = (e) => {
      tx = (e.clientX / window.innerWidth - 0.5) * 2;
      ty = (e.clientY / window.innerHeight - 0.5) * 2;
    };
    window.addEventListener("mousemove", onMove);

    const unsubscribe = subscribe({
      step: (dt) => {
        integrateSpring(sx, tx, omega, zeta, dt);
        integrateSpring(sy, ty, omega, zeta, dt);
      },
      render: () => {
        // Same multipliers as the framer useTransform calls.
        if (titleRef) titleRef.style.transform = `translate3d(${(sx.x * 24).toFixed(2)}px, ${(sy.x * 14).toFixed(2)}px, 0)`;
        if (bgRef) bgRef.style.transform = `translate3d(${(sx.x * -28).toFixed(2)}px, ${(sy.x * -18).toFixed(2)}px, 0)`;
      },
      settled: () =>
        Math.abs(sx.x - tx) < 0.001 && Math.abs(sy.x - ty) < 0.001 &&
        Math.abs(sx.v) < 0.001 && Math.abs(sy.v) < 0.001,
    });

    onCleanup(() => {
      window.removeEventListener("mousemove", onMove);
      unsubscribe();
    });
  });

  const enter = () => {
    window.location.href = isAuthenticated() ? "/home" : "/login";
  };

  const marqueeRun = () => (
    <For each={Array.from({ length: 6 })}>
      {() => (
        <span class="flex items-center tech-label">
          <span class="px-6">SECONDARY COMMUNITY MEETING</span>
          <Plus class="h-3 w-3 text-primary/70" />
          <span class="px-6">FRIDAY WEEKLY</span>
          <Plus class="h-3 w-3 text-primary/70" />
          <span class="px-6">MABIS BANGKOK</span>
          <Plus class="h-3 w-3 text-primary/70" />
        </span>
      )}
    </For>
  );

  return (
    <div class="relative min-h-screen w-full overflow-hidden bg-ink text-bone">
      <div ref={bgRef} class="absolute inset-0">
        <KineticBackground variant="ink" />
      </div>

      {/* top bar */}
      <Enter
        delay={0.2}
        duration={0.6}
        fromY={-20}
        class="absolute left-0 right-0 top-0 z-30 flex items-center justify-between px-4 py-4 sm:px-8 sm:py-5"
      >
        <div class="flex items-center gap-3">
          <span class="flex h-8 w-8 items-center justify-center border border-bone/30">
            <img src={LOGO} alt="MABIS" class="h-5 w-5 object-contain" />
          </span>
          <span class="tech-label text-bone/60">
            <span class="sm:hidden">MABIS</span>
            <span class="hidden sm:inline">MABIS COMMUNITY MEETING</span>
          </span>
        </div>
        <span class="tech-label hidden sm:block text-bone/50">EST. BANGKOK TH</span>
      </Enter>

      {/* vertical side labels */}
      <Enter
        delay={1}
        duration={0.8}
        fromY={20}
        class="vert-text tech-label absolute left-5 sm:left-8 top-1/2 -translate-y-1/2 text-bone/45 z-20 hidden md:block"
      >
        SECONDARY COMMUNITY
      </Enter>
      <Enter
        delay={1.1}
        duration={0.8}
        fromY={-20}
        class="vert-text tech-label absolute right-5 sm:right-8 top-1/2 -translate-y-1/2 text-bone/45 z-20 hidden md:block"
      >
        N° 2026 EDITION
      </Enter>

      {/* crosshair decorations */}
      <Enter delay={0.6} duration={0.6} class="pointer-events-none absolute inset-5 sm:inset-8 corner-bracket z-20" />
      <Plus class="absolute top-1/3 right-1/4 h-2.5 w-2.5 text-primary/60 z-20" />

      {/* center stage with pointer parallax */}
      <div class="relative z-10 flex min-h-[100dvh] flex-col items-start justify-center px-4 pb-20 pt-20 sm:min-h-screen sm:items-center sm:px-8 sm:pb-0 sm:pt-0">
        {/* giant cropped background word */}
        <Enter
          delay={0.4}
          duration={1.2}
          toOpacity={0.05}
          class="pointer-events-none absolute top-[14%] left-1/2 -translate-x-1/2 font-display font-thin tracking-ultra text-bone leading-none select-none whitespace-nowrap huge-crop"
        >
          MABIS
        </Enter>

        <Enter delay={0.5} duration={0.6} fromY={8} class="mb-4 flex max-w-full items-center gap-3 tech-label text-primary sm:mb-6">
          <Enter delay={0.55} duration={0.6} fromScaleX={0} class="block h-px w-8 bg-primary origin-left" />
          <span>01 —</span>
          <JapaneseText
            ja="セカンダリー・コミュニティ・ミーティング・アプリ"
            layout="inline"
            japaneseClass="ml-1.5 inline normal-case tracking-normal text-[0.85em]"
          >
            SECONDARY COMMUNITY MEETING APP
          </JapaneseText>
        </Enter>

        <div ref={titleRef} class="will-change-transform">
          <h1 class="text-left font-display text-[clamp(2.8rem,14vw,4.1rem)] font-extralight leading-[0.88] tracking-ultra sm:text-center sm:text-8xl md:text-9xl lg:text-[11rem]">
            <span class="block">
              <SplitChars text="COMMUNITY" stagger={0.05} delay={0.6} />
            </span>
            <span class="block mt-2 sm:mt-3 text-stroke-bone">
              <SplitChars text="MEETING" stagger={0.05} delay={1.0} />
            </span>
          </h1>
        </div>

        <Enter
          delay={1.6}
          duration={0.8}
          fromScaleX={0}
          class="my-6 h-px w-32 origin-left bg-bone/40 sm:my-10 sm:w-40 sm:origin-center"
        />

        <Enter delay={1.7} duration={0.7} fromY={10} class="max-w-md text-left sm:text-center text-sm sm:text-base text-bone/65 leading-relaxed">
          <JapaneseText
            ja="自分の言葉を届け、互いに耳を傾け、みんなで決める。中等部のコミュニティが記録し、振り返り、育てていきます。"
            japaneseClass="mt-2 block text-[0.9em]"
          >
            Voice your words with presence and shared decision — recorded, remembered, and refined by the secondary community.
          </JapaneseText>
        </Enter>

        <div class="mt-7 w-full sm:mt-12 sm:w-auto">
          <MagneticButton strength={0.4}>
            <button
              onClick={enter}
              data-cursor="ENTER"
              class="liquid-btn liquid-ink group relative flex w-full items-center justify-between gap-3 border border-bone/40 bg-bone/5 px-5 py-4 text-bone backdrop-blur-sm sm:w-auto sm:justify-start sm:gap-4 sm:px-8"
            >
              <span class="tech-label">N° 02</span>
              <span class="text-lg sm:text-xl font-display font-normal tracking-tight">
                {isAuthenticated() ? "ENTER START" : "ENTER LOG IN"}
              </span>
              <span class="relative flex h-8 w-8 items-center justify-center overflow-hidden">
                <ArrowUpRight class="h-6 w-6" />
              </span>
            </button>
          </MagneticButton>
        </div>

        {/* scroll cue */}
        <Enter delay={0.4} duration={0.6} class="absolute bottom-16 right-5 hidden flex-col items-center gap-2 sm:right-10 sm:flex">
          <span class="tech-label vert-text text-bone/45">SCROLL</span>
          <span class="splash-bob">
            <ArrowDown class="h-4 w-4 text-bone/50" />
          </span>
        </Enter>
      </div>

      {/* bottom marquee */}
      <div class="absolute bottom-0 left-0 right-0 z-10 border-t border-bone/15 py-3 bg-ink/80 backdrop-blur-sm">
        <Marquee speed={32} class="text-bone/55">
          {marqueeRun}
        </Marquee>
      </div>
    </div>
  );
}
