// src/components/wheel/SpinWheel.jsx
import React, { useState, useRef, useEffect } from "react";
import { motion } from "framer-motion";
import confetti from "canvas-confetti";
import { playWheelTick, playWheelStart, playWheelWin } from "@/lib/wheel_sound";
import OpenMoji from "@/components/OpenMoji";

const WHEEL_COLORS = [
  "#8B5CF6", "#EC4899", "#3B82F6", "#10B981",
  "#F59E0B", "#EF4444", "#06B6D4", "#6366F1",
  "#14B8A6", "#F97316", "#A855F7", "#84CC16"
];

export default function SpinWheel({ members, onResult }) {
  const [spinning, setSpinning] = useState(false);
  const [rotation, setRotation] = useState(0);
  const [winner, setWinner] = useState(null);
  const canvasRef = useRef(null);

  const segmentAngle = members.length > 0 ? 360 / members.length : 360;

  useEffect(() => {
    drawWheel();
    const handleFontChange = () => drawWheel();
    window.addEventListener("fontChanged", handleFontChange);
    return () => window.removeEventListener("fontChanged", handleFontChange);
  }, [members, rotation]);

  const drawWheel = () => {
    const canvas = canvasRef.current;
    if (!canvas || members.length === 0) return;
    const ctx = canvas.getContext("2d");
    const size = canvas.width;
    const center = size / 2;
    const radius = center - 8;

    ctx.clearRect(0, 0, size, size);

    // Draw shadow
    ctx.beginPath();
    ctx.arc(center, center + 4, radius, 0, Math.PI * 2);
    ctx.fillStyle = "rgba(0,0,0,0.1)";
    ctx.fill();

    members.forEach((member, i) => {
      const startAngle = (i * segmentAngle - 90 + rotation) * (Math.PI / 180);
      const endAngle = ((i + 1) * segmentAngle - 90 + rotation) * (Math.PI / 180);

      // Segment
      ctx.beginPath();
      ctx.moveTo(center, center);
      ctx.arc(center, center, radius, startAngle, endAngle);
      ctx.closePath();
      ctx.fillStyle = WHEEL_COLORS[i % WHEEL_COLORS.length];
      ctx.fill();

      // Border
      ctx.strokeStyle = "rgba(255,255,255,0.3)";
      ctx.lineWidth = 2;
      ctx.stroke();

      // Text
      const textAngle = startAngle + (endAngle - startAngle) / 2;
      const textRadius = radius * 0.65;
      const textX = center + Math.cos(textAngle) * textRadius;
      const textY = center + Math.sin(textAngle) * textRadius;

      ctx.save();
      ctx.translate(textX, textY);
      ctx.rotate(textAngle + Math.PI / 2);
      ctx.fillStyle = "white";
      const uiFont = getComputedStyle(document.documentElement).getPropertyValue("--font-body").trim() || "'GNUFreeMonoUI'";
      ctx.font = `bold ${Math.max(10, Math.min(14, 200 / members.length))}px ${uiFont}`;
      ctx.textAlign = "center";
      ctx.textBaseline = "middle";
      
      const name = member.name.length > 10 ? member.name.slice(0, 9) + "…" : member.name;
      ctx.fillText(name, 0, 0);
      ctx.restore();
    });

    // Center circle
    ctx.beginPath();
    ctx.arc(center, center, 24, 0, Math.PI * 2);
    ctx.fillStyle = "#1e1b4b";
    ctx.fill();
    ctx.beginPath();
    ctx.arc(center, center, 20, 0, Math.PI * 2);
    const grad = ctx.createRadialGradient(center, center, 0, center, center, 20);
    grad.addColorStop(0, "#8B5CF6");
    grad.addColorStop(1, "#6D28D9");
    ctx.fillStyle = grad;
    ctx.fill();
  };

  const spin = () => {
    if (spinning || members.length === 0) return;
    setSpinning(true);
    setWinner(null);
    playWheelStart();

    const extraSpins = 5 + Math.random() * 5;
    const targetAngle = Math.random() * 360;
    const totalRotation = extraSpins * 360 + targetAngle;

    let startTime = null;
    const duration = 4000;
    const startRotation = rotation;

    const easeOut = (t) => 1 - Math.pow(1 - t, 4);

    // one wooden knock each time a segment edge crosses the pointer
    let lastSegment = Math.floor(startRotation / segmentAngle);

    const animate = (timestamp) => {
      if (!startTime) startTime = timestamp;
      const elapsed = timestamp - startTime;
      const progress = Math.min(elapsed / duration, 1);
      const easedProgress = easeOut(progress);

      const currentRotation = startRotation + totalRotation * easedProgress;
      setRotation(currentRotation % 360);

      const segment = Math.floor(currentRotation / segmentAngle);
      if (segment !== lastSegment) {
        lastSegment = segment;
        playWheelTick(progress);
      }

      if (progress < 1) {
        requestAnimationFrame(animate);
      } else {
        const finalAngle = (360 - (currentRotation % 360) + 90) % 360;
        const winnerIndex = Math.floor(finalAngle / segmentAngle) % members.length;
        const selectedMember = members[winnerIndex];
        setWinner(selectedMember);
        setSpinning(false);
        playWheelWin();

        confetti({
          particleCount: 150,
          spread: 80,
          origin: { y: 0.5 },
          colors: ["#8B5CF6", "#EC4899", "#3B82F6", "#10B981", "#F59E0B"],
        });

        if (onResult) onResult(selectedMember);
      }
    };

    requestAnimationFrame(animate);
  };

  return (
    <div className="flex flex-col items-center gap-6">
      <div className="relative">
        {/* Pointer */}
        <div className="absolute -top-2 left-1/2 -translate-x-1/2 z-10">
          <div className="w-0 h-0 border-l-[14px] border-r-[14px] border-t-[24px] border-l-transparent border-r-transparent border-t-foreground drop-shadow-lg" />
        </div>
        <canvas
          ref={canvasRef}
          width={320}
          height={320}
          className="rounded-full shadow-2xl shadow-primary/20 cursor-pointer"
          onClick={spin}
        />
        {/* Glow */}
        <div className="absolute inset-0 rounded-full bg-primary/5 blur-3xl -z-10 scale-125" />
      </div>

      <motion.button
        onClick={spin}
        disabled={spinning || members.length === 0}
        whileHover={{ scale: 1.05 }}
        whileTap={{ scale: 0.95 }}
        className="px-8 py-3 rounded-2xl font-display font-bold text-white bg-gradient-to-r from-primary to-accent shadow-lg shadow-primary/30 disabled:opacity-50 disabled:cursor-not-allowed text-lg tracking-wide"
      >
        {spinning ? (
          <span className="flex items-center gap-2">
            <OpenMoji hexcode="1F3B0" className="h-5 w-5" />
            Spinning...
          </span>
        ) : (
          <span className="flex items-center gap-2">
            <OpenMoji hexcode="1F3AF" className="h-5 w-5" />
            SPIN THE WHEEL
          </span>
        )}
      </motion.button>

      {winner && (
        <motion.div
          initial={{ opacity: 0, scale: 0.8, y: 20 }}
          animate={{ opacity: 1, scale: 1, y: 0 }}
          className="text-center p-4 rounded-2xl bg-gradient-to-r from-primary/10 to-accent/10 border border-primary/20"
        >
          <p className="flex items-center justify-center gap-1.5 text-sm text-muted-foreground font-medium">
            <OpenMoji hexcode="1F389" className="h-4 w-4" />
            Selected
          </p>
          <p className="text-2xl font-display font-bold text-foreground mt-1">{winner.name}</p>
        </motion.div>
      )}
    </div>
  );
}

// solid/components/jobs/SpinWheel.jsx
import { createSignal, onMount, onCleanup, Show } from "solid-js";
import { Loader2 } from "lucide-solid";
import { displayName } from "@/lib/names";
import { playWheelTick, playWheelStart, playWheelWin } from "@/lib/wheel_sound";
import { Button } from "~/components/ui";

/*
 * SpinWheel — Solid port from src/components/JobsWidget.jsx.
 *
 * The canvas drawing and the spin animation are vanilla and carry over
 * verbatim. What disappears is the React scaffolding around them:
 *
 *   useRef(x)     → a plain `let`. Refs exist in React because a re-render
 *                   would otherwise reset a local; Solid's component body runs
 *                   once, so a local IS stable.
 *   useCallback   → a plain function. There is no re-render to memoise
 *                   against, so drawWheel/refreshAppearance need no wrapper
 *                   and no dependency array.
 *   useEffect     → onMount + onCleanup.
 *
 * The rotation value was already held in a ref rather than state in the React
 * version — deliberately, because writing it to state 60×/sec would re-render
 * the component every frame. In Solid it is simply a local, and the canvas is
 * written to directly, so a spin costs zero reactive work.
 */
export default function SpinWheel(props) {
  let canvasEl;
  let rotation = 0;
  let spinning = false;
  let raf = null;
  let appearanceRaf = null;

  const [isSpinning, setIsSpinning] = createSignal(false);

  const size = () => props.size ?? 360;
  const members = () => props.members || [];

  let appearance = {
    primary: "#951E3A",
    secondary: "#EACE54",
    ring: "#7a1830",
    font: "'GNUFreeMonoUI'",
  };

  const refreshAppearance = () => {
    const styles = getComputedStyle(document.documentElement);
    const themeColor = (name, fallback) => {
      const value = styles.getPropertyValue(name).trim();
      return value ? `hsl(${value})` : fallback;
    };
    appearance = {
      primary: themeColor("--primary", "#951E3A"),
      secondary: themeColor("--secondary", "#EACE54"),
      ring: themeColor("--ring", "#7a1830"),
      font: styles.getPropertyValue("--font-body").trim() || "'GNUFreeMonoUI'",
    };
  };

  const drawWheel = (rot) => {
    const canvas = canvasEl;
    const list = members();
    if (!canvas || list.length === 0) return;

    const s = size();
    const dpr = Math.min(window.devicePixelRatio || 1, 2);
    const backingSize = Math.round(s * dpr);
    if (canvas.width !== backingSize || canvas.height !== backingSize) {
      canvas.width = backingSize;
      canvas.height = backingSize;
    }

    const parentWidth = canvas.parentElement?.clientWidth || s;
    const viewportWidth = typeof window !== "undefined" ? window.innerWidth - 32 : s;
    const displaySize = Math.min(s, parentWidth, viewportWidth);
    const cssSize = `${displaySize}px`;
    if (canvas.style.width !== cssSize) canvas.style.width = cssSize;
    if (canvas.style.height !== cssSize) canvas.style.height = cssSize;

    const ctx = canvas.getContext("2d");
    ctx.setTransform(dpr, 0, 0, dpr, 0, 0);

    const cx = s / 2, cy = s / 2, r = s / 2 - 8;
    const arc = (2 * Math.PI) / list.length;
    ctx.clearRect(0, 0, s, s);

    const { primary: primaryColor, secondary: secondaryColor, ring: primaryDark, font: uiFont } = appearance;

    list.forEach((m, i) => {
      const start = rot + i * arc;
      const end = rot + (i + 1) * arc;
      const isRed = i % 2 === 0;
      ctx.beginPath();
      ctx.moveTo(cx, cy);
      ctx.arc(cx, cy, r, start, end);
      ctx.closePath();
      ctx.fillStyle = isRed ? primaryColor : secondaryColor;
      ctx.fill();
      ctx.strokeStyle = "#ffffff";
      ctx.lineWidth = 2;
      ctx.stroke();

      ctx.save();
      ctx.translate(cx, cy);
      ctx.rotate(start + arc / 2);
      ctx.textAlign = "right";
      const fontSize = list.length > 20 ? 9 : list.length > 14 ? 11 : 13;
      ctx.font = `700 ${fontSize}px ${uiFont}`;
      ctx.shadowColor = "rgba(0,0,0,0.45)";
      ctx.shadowBlur = 2;
      ctx.fillStyle = "#ffffff";
      ctx.fillText(displayName(m), r - 10, 4);
      ctx.shadowBlur = 0;
      ctx.restore();
    });

    // Outer rings
    ctx.beginPath(); ctx.arc(cx, cy, r, 0, 2 * Math.PI);
    ctx.strokeStyle = primaryDark; ctx.lineWidth = 6; ctx.stroke();
    ctx.beginPath(); ctx.arc(cx, cy, r - 2, 0, 2 * Math.PI);
    ctx.strokeStyle = "rgba(255,255,255,0.25)"; ctx.lineWidth = 2; ctx.stroke();

    // Hub
    ctx.beginPath(); ctx.arc(cx, cy, 24, 0, 2 * Math.PI);
    ctx.fillStyle = "rgba(0,0,0,0.15)"; ctx.fill();
    ctx.beginPath(); ctx.arc(cx, cy, 22, 0, 2 * Math.PI);
    ctx.fillStyle = primaryDark; ctx.fill();
    ctx.beginPath(); ctx.arc(cx, cy, 14, 0, 2 * Math.PI);
    ctx.fillStyle = secondaryColor; ctx.fill();
    ctx.beginPath(); ctx.arc(cx, cy, 6, 0, 2 * Math.PI);
    ctx.fillStyle = "#fff"; ctx.fill();
  };

  onMount(() => {
    refreshAppearance();
    drawWheel(rotation);

    const redraw = () => drawWheel(rotation);
    const scheduleAppearanceRedraw = () => {
      if (appearanceRaf) return;
      appearanceRaf = requestAnimationFrame(() => {
        appearanceRaf = null;
        refreshAppearance();
        redraw();
      });
    };

    window.addEventListener("themeChanged", scheduleAppearanceRedraw);
    window.addEventListener("fontChanged", scheduleAppearanceRedraw);
    window.addEventListener("resize", redraw, { passive: true });

    onCleanup(() => {
      window.removeEventListener("themeChanged", scheduleAppearanceRedraw);
      window.removeEventListener("fontChanged", scheduleAppearanceRedraw);
      window.removeEventListener("resize", redraw);
      if (appearanceRaf) cancelAnimationFrame(appearanceRaf);
      if (raf) cancelAnimationFrame(raf);
    });
  });

  // Pointer at top (12 o'clock = -π/2) — wheelofnames style
  const POINTER_ANGLE = -Math.PI / 2;

  const handleSpin = () => {
    const list = members();
    if (spinning || list.length === 0 || props.disabled) return;
    spinning = true;
    setIsSpinning(true);
    playWheelStart();

    const fullRotations = 5 + Math.random() * 3;
    const totalRot = Math.PI * 2 * fullRotations;
    const duration = 5500 + Math.random() * 1500; // 5.5–7s
    const start = performance.now();
    const startRot = rotation;
    const arc = (2 * Math.PI) / list.length;

    // Quintic ease-out for ultra-smooth deceleration
    const easeOut = (t) => 1 - Math.pow(1 - t, 5);

    const segmentAt = (rot) => {
      let diff = (POINTER_ANGLE - rot) % (2 * Math.PI);
      while (diff < 0) diff += 2 * Math.PI;
      return Math.floor(diff / arc) % list.length;
    };

    // one wooden knock each time a segment edge passes the pointer
    let lastSeg = segmentAt(startRot);

    const animate = (now) => {
      const p = Math.min((now - start) / duration, 1);
      rotation = startRot + totalRot * easeOut(p);
      drawWheel(rotation);
      const seg = segmentAt(rotation);
      if (seg !== lastSeg) {
        lastSeg = seg;
        playWheelTick(p);
      }
      if (p < 1) {
        raf = requestAnimationFrame(animate);
      } else {
        spinning = false;
        setIsSpinning(false);
        playWheelWin();
        props.onSpinComplete(list[segmentAt(rotation)]);
      }
    };
    raf = requestAnimationFrame(animate);
  };

  return (
    <div class="flex flex-col items-center gap-4">
      <div class="relative inline-block w-full max-w-full">
        {/* Pointer at top — wheelofnames style */}
        <div
          class="absolute -top-2 left-1/2 -translate-x-1/2 z-10 drop-shadow-lg"
          style={{
            width: 0, height: 0,
            "border-left": "14px solid transparent",
            "border-right": "14px solid transparent",
            "border-top": "28px solid hsl(var(--ring))",
          }}
        />
        <canvas
          ref={canvasEl}
          style={{
            width: `${size()}px`,
            height: `${size()}px`,
            "box-shadow": "0 8px 40px hsl(var(--primary) / 0.3), 0 2px 8px rgba(0,0,0,0.12)",
          }}
          class="cursor-pointer rounded-full"
          onClick={handleSpin}
        />
      </div>

      <Button
        onClick={handleSpin}
        disabled={isSpinning() || members().length === 0 || props.disabled}
        class="bg-primary hover:bg-primary/90 text-primary-foreground rounded-xl px-10 text-base font-bold w-full"
        size="lg"
      >
        <Show when={isSpinning()} fallback={"Spin"}>
          <Loader2 class="w-4 h-4 animate-spin mr-2" />Spinning...
        </Show>
      </Button>
    </div>
  );
}
