// solid/pages/Home.jsx
import { createSignal, onMount, onCleanup, lazy, Suspense, For, Show } from "solid-js";
import { format, getISOWeek, getISOWeekYear } from "date-fns";
import { LazySection, EditorialSection, HomeSectionIndex, HomeMasthead } from "~/components/home/shell";
import { useQuery } from "@tanstack/solid-query";
import { Settings, Palette, CircleHelp } from "lucide-solid";
import { base44 } from "@/api/base44Client";
import { installScrollStateClass } from "~/lib/perf";
import { useAuth } from "~/lib/AuthContext";
import { usePresenceHeartbeat } from "~/lib/usePresence";
import SiteHeader from "~/components/SiteHeader";
import ThemeSwitcher from "~/components/ThemeSwitcher";
import IdleMount from "~/components/IdleMount";
import ScrollVelocity from "~/components/ScrollVelocity";
import ScrollScaleRitual from "~/components/home/ScrollScaleRitual";
import BirthdayBanner from "~/components/BirthdayBanner";
import { ScrollSectionIndicator } from "~/components/chrome";
import { PageFooter } from "~/components/page-chrome";

const SettingsModal = lazy(() => import("~/components/SettingsModal"));
const MabisAIAssistant = lazy(() => import("~/components/MabisAIAssistant"));
const FeedbackWidget = lazy(() => import("~/components/FeedbackWidget"));
const ProfileEditor = lazy(() => import("~/components/ProfileEditor"));
const JobReminder = lazy(() => import("~/components/JobReminder"));

// Memoised so hover/focus/pointerdown all warm the same import rather than
// queueing three, matching the React page's preloadQuickStartGuide.
let quickStartModulePromise;
const preloadQuickStartGuide = () => (quickStartModulePromise ||= import("~/components/QuickStartGuide"));
const QuickStartGuide = lazy(preloadQuickStartGuide);

const MABIS_LOGO = "https://media.base44.com/images/public/6a2fcc3f4fec7200fed7a889/b6064da4f_MabisLogo-800x800.png/v1/fill/w_144,h_144/logo.webp";

const ROLE_COLOR_VARS = {
  student: "hsl(var(--role-student))",
  teacher: "hsl(var(--role-teacher))",
  chair: "hsl(var(--role-chair))",
  minutes: "hsl(var(--role-minutes))",
  admin: "hsl(var(--role-admin))",
  editor: "hsl(var(--role-editor))",
};

// Widgets are code-split individually, so a section that never scrolls into
// view never downloads its chunk. Combined with LazySection's shared observer
// this means first paint pays for the masthead and index only.
const LunchMenuWidget = lazy(() => import("~/components/LunchMenuWidget"));
const ScheduleWidget = lazy(() => import("~/components/ScheduleWidget"));
const JobsWidget = lazy(() => import("~/components/JobsWidget"));
const DiscussionWidget = lazy(() => import("~/components/DiscussionWidget"));
const CalendarWidget = lazy(() => import("~/components/CalendarWidget"));
const AnnouncementsWidget = lazy(() => import("~/components/AnnouncementsWidget"));
const NewsWidget = lazy(() => import("~/components/NewsWidget"));
const MeetingModeWidget = lazy(() => import("~/components/MeetingModeWidget"));
const MissingItemsWidget = lazy(() => import("~/components/MissingItemsWidget"));
const MembersWidget = lazy(() => import("~/components/MembersWidget"));

/**
 * Home — SolidJS port of src/pages/Home.jsx (shell).
 *
 * The ten editorial sections and their copy are carried over verbatim,
 * including the Japanese companion text. Widgets are mounted through
 * LazySection exactly as before; each one is its own migration task, so they
 * render as reserved placeholders here rather than being faked.
 *
 * Why this page is cheap to scroll:
 *   · every section is `content-visibility: auto`, so off-screen sections are
 *     skipped for layout and paint entirely;
 *   · one shared IntersectionObserver drives all ten sections, not ten;
 *   · the only scroll listener on the page is passive and rAF-coalesced, and
 *     it writes a class rather than touching the reactive graph;
 *   · nothing here reads layout (offsetTop/getBoundingClientRect) during
 *     scroll, so there is no forced synchronous layout.
 */

const SECTIONS = [
  {
    index: "01", label: "MEETING MODE", jaLabel: "ミーティング開始", height: 320,
    description: "Starts the Friday meeting for everyone at once. The chair or a teacher presses this — then the whole group follows the same screen.",
    jaDescription: "金曜日のミーティングを全員同時に始めます。司会か先生がボタンを押すと、みんなが同じ画面を見ながら進みます。",
  },
  {
    index: "02", label: "ANNOUNCEMENTS", jaLabel: "お知らせ", height: 360,
    description: "Short notices from teachers and staff. The newest one is always at the top.",
    jaDescription: "先生やスタッフからの短いお知らせです。新しいものが常に一番上に表示されます。",
  },
  {
    index: "03", label: "DISCUSSION", jaLabel: "話し合い", height: 560,
    description: "Anything you want the group to talk about on Friday. Anyone can add one — write your topic and pick your name.",
    jaDescription: "金曜日にみんなで話し合いたいことを書きます。誰でも追加できます。テーマを書いて名前を選んでください。",
  },
  {
    index: "04", label: "JOBS AND ROTATION", jaLabel: "係とローテーション", height: 560,
    description: "Who is doing which job, and when your turn comes round. Tick your job off once you have done it.",
    jaDescription: "誰がどの係をしているか、自分の番がいつ来るかがわかります。終わったらチェックを入れてください。",
  },
  {
    index: "05", label: "CALENDAR", jaLabel: "カレンダー", height: 620,
    description: "Events, holidays and birthdays coming up. Tap any day to see what is on.",
    jaDescription: "これからの予定・祝日・誕生日がわかります。日付をタップすると詳しい内容が見られます。",
  },
  {
    index: "06", label: "SCHEDULE", jaLabel: "スケジュール", height: 420,
    description: "The normal class timetable for the week.",
    jaDescription: "今週のふだんの時間割です。",
  },
  {
    index: "07", label: "LOST AND FOUND", jaLabel: "落とし物", height: 420,
    description: "Lost something? Add it here so people can look out for it. Found something? Check whether anyone is missing it.",
    jaDescription: "何かなくしましたか？ここに追加すると、みんなが気にかけてくれます。何かを見つけたら、探している人がいないか確認してください。",
  },
  {
    index: "08", label: "LUNCH MENU", jaLabel: "ランチメニュー", height: 420,
    description: "What is for snack and lunch on each day this week.",
    jaDescription: "今週の各曜日のおやつとランチの内容です。",
  },
  {
    index: "09", label: "NEWS", jaLabel: "ニュース", height: 480,
    description: "Longer stories and updates from around the school.",
    jaDescription: "学校のいろいろな出来事についての、少し長めの記事です。",
  },
  {
    index: "10", label: "MEMBERS", jaLabel: "メンバー", height: 560,
    description: "Everyone in the community, and the job or role each person has right now.",
    jaDescription: "コミュニティの全員と、それぞれが今担当している係や役割がわかります。",
  },
];

const WIDGETS = {
  "01": MeetingModeWidget,
  "02": AnnouncementsWidget,
  "03": DiscussionWidget,
  "04": JobsWidget,
  "05": CalendarWidget,
  "06": ScheduleWidget,
  "08": LunchMenuWidget,
  "07": MissingItemsWidget,
  "09": NewsWidget,
  "10": MembersWidget,
};

export default function Home() {
  const auth = useAuth();
  const isAdmin = () => {
    const role = auth.user()?.role_override || auth.user()?.role;
    return role === "admin" || role === "editor";
  };

  // Fetched once here and passed down, mirroring the React page: the widgets
  // that need the roster all share this single query rather than each issuing
  // its own.
  const membersQuery = useQuery(() => ({
    queryKey: ["members"],
    queryFn: () => base44.entities.Member.list("name", 200),
  }));
  const members = () => membersQuery.data || [];

  const [showSettings, setShowSettings] = createSignal(false);
  const [editingProfile, setEditingProfile] = createSignal(false);
  const [showHelp, setShowHelp] = createSignal(false);

  const effectiveRole = () => auth.user()?.role_override || auth.user()?.role;
  const roleColor = () => ROLE_COLOR_VARS[effectiveRole()] || "hsl(var(--primary))";
  usePresenceHeartbeat();

  // Warm the Settings chunk on hover/focus so the first click is not spent
  // waiting on a network fetch — same fix applied to the React build.
  const preloadSettings = () => { void import("~/components/SettingsModal"); };

  // A function, not an element: SiteHeader renders this in two places
  // (desktop bar + mobile drawer), and in Solid the same nodes cannot occupy
  // both — they would move rather than duplicate.
  const controls = () => (
    <>
      <ThemeSwitcher />
      <button
        onClick={() => setShowHelp(true)}
        onMouseEnter={preloadQuickStartGuide}
        onFocus={preloadQuickStartGuide}
        onPointerDown={preloadQuickStartGuide}
        data-cursor="HELP"
        title="How to use this site"
        class="flex h-9 items-center justify-center gap-1.5 border border-foreground/30 bg-background px-2.5 text-foreground transition-colors hover:bg-foreground hover:text-background"
      >
        <CircleHelp class="w-4 h-4" />
        <span class="hidden text-[10px] font-bold uppercase tracking-wide sm:inline">Help</span>
      </button>
      <button
        onMouseEnter={preloadSettings}
        onFocus={preloadSettings}
        onPointerDown={preloadSettings}
        onClick={() => setShowSettings(true)}
        data-cursor="SET"
        title="Settings"
        class="h-9 w-9 flex items-center justify-center border border-foreground/30 bg-background text-foreground hover:bg-foreground hover:text-background transition-colors"
      >
        <Settings class="w-4 h-4" />
      </button>

      <div class="flex items-center gap-2.5 pl-1">
        <div class="relative shrink-0">
          <div
            class="h-9 w-9 overflow-hidden flex items-center justify-center bg-card"
            style={{ border: `2px solid ${roleColor()}`, "box-sizing": "border-box" }}
          >
            <Show
              when={auth.user()?.avatar_url}
              fallback={<img src={MABIS_LOGO} alt="avatar" class="w-full h-full object-contain p-0.5" />}
            >
              <img src={auth.user().avatar_url} alt="avatar" class="w-full h-full object-cover" />
            </Show>
          </div>
          <button
            onClick={() => setEditingProfile(!editingProfile())}
            title="Customize Profile Picture"
            class="absolute -bottom-1 -right-1 h-5 w-5 flex items-center justify-center bg-card border border-foreground/30 text-primary"
          >
            <Palette class="w-3 h-3" />
          </button>
        </div>
        <span class="text-xs tech-label text-foreground hidden lg:inline">
          {auth.user()?.full_name?.split(" ")[0]?.toUpperCase() || "USER"}
        </span>
        <button
          onClick={() => auth.logout()}
          data-cursor="EXIT"
          class="liquid-btn tech-label px-3.5 py-2 border border-foreground/30 bg-background text-foreground"
        >
          SIGN OUT
        </button>
      </div>
    </>
  );

  onMount(() => {
    const stop = installScrollStateClass();
    onCleanup(stop);
  });

  // Computed once. Not signals — nothing here changes after mount, so putting
  // it in the reactive graph would only add cost.
  const now = new Date();
  const weekLabel = `${getISOWeekYear(now)}-W${String(getISOWeek(now)).padStart(2, "0")}`;
  const dateLabel = format(now, "dd.MM.yyyy");

  return (
    <div class="editorial-home min-h-screen bg-background overflow-x-hidden">
      <SiteHeader rightSlot={controls} />
      <ScrollSectionIndicator total={10} />

      <Show when={showHelp()}>
        <Suspense fallback={null}>
          <QuickStartGuide open onClose={() => setShowHelp(false)} />
        </Suspense>
      </Show>

      <Show when={editingProfile()}>
        <Suspense fallback={null}>
          <ProfileEditor open onClose={() => setEditingProfile(false)} />
        </Suspense>
      </Show>

      <Show when={showSettings()}>
        <Suspense fallback={null}>
          <SettingsModal open onClose={() => setShowSettings(false)} isAdmin={isAdmin()} />
        </Suspense>
      </Show>

      <main class="mx-auto max-w-[1600px] px-4 pb-8 pt-20 sm:px-10 sm:pt-32">
        <HomeMasthead weekLabel={weekLabel} dateLabel={dateLabel} date={now} />

        <div class="pb-6 pt-5 sm:pb-10 sm:pt-8">
          <HomeSectionIndex />
        </div>

        <div class="space-y-12 sm:space-y-24">
          <For each={SECTIONS}>
            {(s) => (
              <EditorialSection
                index={s.index}
                label={s.label}
                jaLabel={s.jaLabel}
                description={s.description}
                jaDescription={s.jaDescription}
                intrinsicHeight={s.height + 160}
              >
                <LazySection minHeight={s.height}>
                  {/* Ported widgets render here; the rest still reserve their
                      exact final height, so swapping one in shifts nothing. */}
                  <Show
                    when={WIDGETS[s.index]}
                    fallback={
                      <div
                        class="lazy-section-placeholder"
                        style={{
                          "--lazy-min-height": `${s.height}px`,
                          "contain-intrinsic-size": `auto ${s.height}px`,
                        }}
                        aria-hidden
                      />
                    }
                  >
                    {(Widget) => (
                      <Suspense
                        fallback={
                          <div
                            class="lazy-section-placeholder"
                            style={{ "--lazy-min-height": `${s.height}px` }}
                            aria-hidden
                          />
                        }
                      >
                        {(() => {
                          const W = Widget();
                          return (
                            <W
                              isAdmin={isAdmin()}
                              members={members()}
                              canChangeRoles={isAdmin()}
                              canStart={isAdmin()}
                              onStartMeeting={() => window.dispatchEvent(new CustomEvent("startMeetingMode"))}
                            />
                          );
                        })()}
                      </Suspense>
                    )}
                  </Show>
                </LazySection>
              </EditorialSection>
            )}
          </For>
        </div>
      </main>

      {/* Deferred until the browser is idle, as in React — same three, same order. */}
      <IdleMount timeout={1800}>
        <Suspense fallback={null}>
          <JobReminder />
          <MabisAIAssistant />
          <FeedbackWidget />
        </Suspense>
      </IdleMount>
    </div>
  );
}

// src/pages/Home.jsx
import React, { lazy, Suspense, useEffect, useMemo, useState } from "react";
import { useAuth } from "@/lib/AuthContext";
import { useQuery } from "@tanstack/react-query";
import { base44 } from "@/api/base44Client";
import { CircleHelp, Palette, Inbox, Settings } from "lucide-react";
import { format, getISOWeek, getISOWeekYear } from "date-fns";
import PageFooter from "@/components/PageFooter";
import { Link } from "react-router-dom";
import SiteHeader from "@/components/SiteHeader";
import EditorialSection from "@/components/home/EditorialSection";
import LazySection from "@/components/home/LazySection";
import HomeMasthead from "@/components/home/HomeMasthead";
import HomeSectionIndex from "@/components/home/HomeSectionIndex";
import ScrollVelocity from "@/components/ScrollVelocity";
import ScrollScaleRitual from "@/components/home/ScrollScaleRitual";
import ScrollSectionIndicator from "@/components/ScrollSectionIndicator";
import MeetingModeWidget from "@/components/MeetingModeWidget";
import ThemeSwitcher from "@/components/ThemeSwitcher";
import IdleMount from "@/components/IdleMount";
import RoleSwitcher from "@/components/RoleSwitcher";
import RolePreviewToggle from "@/components/RolePreviewToggle";
import BirthdayBanner from "@/components/BirthdayBanner";
import { usePresenceHeartbeat } from "@/hooks/usePresence";
import { matchingMembers, primaryMember } from "@/lib/memberIdentity";

const AnnouncementsWidget = lazy(() => import("@/components/AnnouncementsWidget"));
// Discussion is visible early and user-critical. Start its split chunk as soon
// as Home evaluates, rather than waiting for React render or scroll proximity.
const discussionModule = import("@/components/DiscussionWidget");
const DiscussionWidget = lazy(() => discussionModule);
const MembersWidget = lazy(() => import("@/components/MembersWidget"));
const CalendarWidget = lazy(() => import("@/components/CalendarWidget"));
const JobsWidget = lazy(() => import("@/components/JobsWidget"));
const NewsWidget = lazy(() => import("@/components/NewsWidget"));
const MissingItemsWidget = lazy(() => import("@/components/MissingItemsWidget"));
const LunchMenuWidget = lazy(() => import("@/components/LunchMenuWidget"));
const ScheduleWidget = lazy(() => import("@/components/ScheduleWidget"));
const MabisAIAssistant = lazy(() => import("@/components/MabisAIAssistant"));
const FeedbackWidget = lazy(() => import("@/components/FeedbackWidget"));
const ProfileEditor = lazy(() => import("@/components/ProfileEditor"));
const JobReminder = lazy(() => import("@/components/JobReminder"));
const SettingsModal = lazy(() => import("@/components/SettingsModal"));
const QuickStartGuide = lazy(() => import("@/components/QuickStartGuide"));

function WidgetFallback({ minHeight = 320 }) {
  return <div className="widget-loading-shell" style={{ "--widget-fallback-height": `${minHeight}px` }} aria-hidden />;
}

const MABIS_LOGO = "https://media.base44.com/images/public/6a2fcc3f4fec7200fed7a889/b6064da4f_MabisLogo-800x800.png";

const ROLE_COLOR_VARS = {
  student: "hsl(var(--role-student))",
  teacher: "hsl(var(--role-teacher))",
  chair: "hsl(var(--role-chair))",
  minutes: "hsl(var(--role-minutes))",
  admin: "hsl(var(--role-admin))",
  editor: "hsl(var(--role-editor))",
};

export default function Home() {
  const { user, refetchUser, logout } = useAuth();
  usePresenceHeartbeat();
  const isSummerOrBenjamin = user?.email === "summer@montessoribkk.com" || /benjamin/i.test(user?.full_name || "") || /benjamin/i.test(user?.email || "");
  const userRole = user?.role_override || user?.role;

  const { data: members = [] } = useQuery({
    queryKey: ["members"],
    queryFn: () => base44.entities.Member.list("name", 200)
  });

  // A person may hold several Member rows. Resolve them all, then let the
  // highest-ranked one speak for them, so a duplicate student row can never
  // mask a minutes-taker row. See @/lib/memberIdentity.
  const { userMatches, userMember, isMinutesTaker } = useMemo(() => {
    const matches = matchingMembers(members, user);
    return {
      userMatches: matches,
      userMember: primaryMember(matches),
      isMinutesTaker: matches.some((candidate) => candidate.role === "minutes"),
    };
  }, [members, user?.email, user?.full_name]);

  const canPreview = userRole === "admin" || userRole === "minutes" || isSummerOrBenjamin || isMinutesTaker;
  const [previewRole, setPreviewRole] = useState(() => localStorage.getItem("mabis_preview_role") || "");
  useEffect(() => {
    if (previewRole) localStorage.setItem("mabis_preview_role", previewRole);
    else localStorage.removeItem("mabis_preview_role");
  }, [previewRole]);
  const effectiveRole = (canPreview && previewRole) ? previewRole : userRole;
  const effectiveMemberRole = (canPreview && previewRole) ? previewRole : (userMember?.role || "");

  const isAdmin = effectiveRole === "admin" || effectiveRole === "editor" || effectiveRole === "chair" || effectiveRole === "minutes" || isMinutesTaker || (isSummerOrBenjamin && effectiveRole !== "student" && effectiveRole !== "teacher");
  const canManage = ["admin", "editor", "chair", "minutes", "teacher"].includes(effectiveRole) || isMinutesTaker || (isSummerOrBenjamin && effectiveRole !== "student");
  useEffect(() => {
    if (isSummerOrBenjamin && (!userRole || userRole === "user")) {
      base44.auth.updateMe({ role_override: "admin" }).then(() => refetchUser?.()).catch(() => {});
    }
  }, [user?.email, user?.full_name, userRole, isSummerOrBenjamin]);

  const [editingProfile, setEditingProfile] = useState(false);
  const [showSettings, setShowSettings] = useState(false);
  const [showHelp, setShowHelp] = useState(false);
  const effectiveAdmin = isAdmin;
  const isFullAdmin = effectiveRole === "admin" || effectiveRole === "editor" || effectiveRole === "minutes" || isMinutesTaker;
  const canSeeInbox = (effectiveRole === "admin" || effectiveRole === "editor") && !isMinutesTaker;
  const roleColor = ROLE_COLOR_VARS[effectiveRole] || "hsl(var(--primary))";

  const { data: newFeedback = [] } = useQuery({
    queryKey: ["feedback", "new"],
    queryFn: () => base44.entities.Feedback.filter({ status: "new" }),
    enabled: canSeeInbox,
  });
  const hasNewFeedback = newFeedback.length > 0;

  const discussionCanManage = canManage || isMinutesTaker;
  const leadRoles = ["admin", "editor", "chair", "minutes", "teacher"];
  const canStartMeeting = canManage || leadRoles.includes(effectiveMemberRole);

  const controls = (
    <>
      {canSeeInbox && (
        <Link to="/feedback" data-cursor="INBOX" title="Feedback & Bug Reports" className="relative flex h-9 w-9 items-center justify-center border border-foreground/30 bg-background text-foreground hover:bg-foreground hover:text-background transition-colors">
          <Inbox className="w-4 h-4" />
          {hasNewFeedback && <span className="absolute -top-1 -right-1 h-2.5 w-2.5 bg-primary" />}
        </Link>
      )}
      {isSummerOrBenjamin ? (
        <RoleSwitcher />
      ) : (
        <>
          {isAdmin && (
            <span className="hidden md:inline tech-label px-2.5 py-1 bg-primary text-primary-foreground">ADMIN</span>
          )}
          {effectiveRole === "editor" && (
            <span className="hidden md:inline tech-label px-2.5 py-1 text-primary-foreground" style={{ backgroundColor: "hsl(var(--role-editor))" }}>EDITOR</span>
          )}
        </>
      )}
      {canPreview && <RolePreviewToggle value={previewRole} onChange={setPreviewRole} realRole={userRole} />}
      <ThemeSwitcher />
      <button
        onClick={() => setShowHelp(true)}
        data-cursor="HELP"
        title="How to use this site"
        className="flex h-9 items-center justify-center gap-1.5 border border-foreground/30 bg-background px-2.5 text-foreground transition-colors hover:bg-foreground hover:text-background"
      >
        <CircleHelp className="w-4 h-4" />
        <span className="hidden text-[10px] font-bold uppercase tracking-wide sm:inline">Help</span>
      </button>
      <button onClick={() => setShowSettings(true)} data-cursor="SET" title="Settings" className="h-9 w-9 flex items-center justify-center border border-foreground/30 bg-background text-foreground hover:bg-foreground hover:text-background transition-colors">
        <Settings className="w-4 h-4" />
      </button>
      <div className="flex items-center gap-2.5 pl-1">
        <div className="relative shrink-0">
          <div className="h-9 w-9 overflow-hidden flex items-center justify-center bg-card"
            style={{ border: `2px solid ${roleColor}`, boxSizing: "border-box" }}>
            {user?.avatar_url
              ? <img src={user.avatar_url} alt="avatar" className="w-full h-full object-cover" />
              : <img src={MABIS_LOGO} alt="avatar" className="w-full h-full object-contain p-0.5" />}
          </div>
          <button onClick={() => setEditingProfile(!editingProfile)} title="Customize Profile Picture" className="absolute -bottom-1 -right-1 h-5 w-5 flex items-center justify-center bg-card border border-foreground/30 text-primary">
            <Palette className="w-3 h-3" />
          </button>
        </div>
        <span className="text-xs tech-label text-foreground hidden lg:inline">
          {user?.full_name?.split(" ")[0]?.toUpperCase() || "USER"}
        </span>
        <button onClick={() => logout()} data-cursor="EXIT" className="liquid-btn tech-label px-3.5 py-2 border border-foreground/30 bg-background text-foreground">
          SIGN OUT
        </button>
      </div>
    </>
  );

  const now = new Date();
  const weekLabel = `${getISOWeekYear(now)}-W${String(getISOWeek(now)).padStart(2, "0")}`;
  const dateLabel = format(now, "dd.MM.yyyy");

  return (
    <div className="editorial-home min-h-screen bg-background overflow-x-hidden">
      <SiteHeader rightSlot={controls} />
      <ScrollSectionIndicator total={10} />
      {editingProfile && (
        <Suspense fallback={null}>
          <ProfileEditor open onClose={() => setEditingProfile(false)} />
        </Suspense>
      )}
      {showSettings && (
        <Suspense fallback={null}>
          <SettingsModal open onClose={() => setShowSettings(false)} isAdmin={effectiveAdmin} />
        </Suspense>
      )}
      {showHelp && (
        <Suspense fallback={null}>
          <QuickStartGuide open onClose={() => setShowHelp(false)} />
        </Suspense>
      )}

      <main className="mx-auto max-w-[1600px] px-4 pb-8 pt-20 sm:px-10 sm:pt-32">
        <HomeMasthead week_label={weekLabel} date_label={dateLabel} />

        <div className="pb-6 pt-5 sm:pb-10 sm:pt-8">
          <HomeSectionIndex />
        </div>

        {/* restrained editorial interlude */}
        <div className="-mx-4 overflow-hidden border-b py-3 jp-rule sm:-mx-10 sm:py-5">
          <ScrollVelocity
            items={["MABIS", "COMMUNITY", "FRIDAY", "BANGKOK"]}
            className="font-display font-light tracking-[-0.035em] text-foreground/16 text-[clamp(1.35rem,7vw,2.15rem)] sm:text-[4.2vw]"
          />
        </div>

        <ScrollScaleRitual />

        <div className="pb-8 pt-4 sm:pb-14 sm:pt-6">
          <BirthdayBanner />
        </div>

        <div className="space-y-12 sm:space-y-24">

        <EditorialSection index="01" label="MEETING MODE" jaLabel="ミーティング開始"
          description="Starts the Friday meeting for everyone at once. The chair or a teacher presses this — then the whole group follows the same screen."
          jaDescription="金曜日のミーティングを全員同時に始めます。司会か先生がボタンを押すと、みんなが同じ画面を見ながら進みます。">
          <MeetingModeWidget canStart={canStartMeeting} onStartMeeting={() => {
            window.dispatchEvent(new CustomEvent("startMeetingMode"));
          }} />
        </EditorialSection>

        <EditorialSection index="02" label="ANNOUNCEMENTS" jaLabel="お知らせ"
          description="Short notices from teachers and staff. The newest one is always at the top."
          jaDescription="先生やスタッフからの短いお知らせです。新しいものが常に一番上に表示されます。">
          <LazySection minHeight={360}>
            <Suspense fallback={<WidgetFallback minHeight={360} />}>
              <AnnouncementsWidget members={members} isAdmin={canManage} />
            </Suspense>
          </LazySection>
        </EditorialSection>

        <EditorialSection index="03" label="DISCUSSION" jaLabel="話し合い"
          description="Anything you want the group to talk about on Friday. Anyone can add one — write your topic and pick your name."
          jaDescription="金曜日にみんなで話し合いたいことを書きます。誰でも追加できます。テーマを書いて名前を選んでください。">
          <Suspense fallback={<WidgetFallback minHeight={560} />}>
            <DiscussionWidget members={members} isAdmin={canManage} canEditTopics={discussionCanManage} />
          </Suspense>
        </EditorialSection>

        <EditorialSection index="04" label="JOBS AND ROTATION" jaLabel="係とローテーション"
          description="Who is doing which job, and when your turn comes round. Tick your job off once you have done it."
          jaDescription="誰がどの係をしているか、自分の番がいつ来るかがわかります。終わったらチェックを入れてください。">
          <LazySection minHeight={560}>
            <Suspense fallback={<WidgetFallback minHeight={560} />}>
              <JobsWidget members={members} isAdmin={canManage} compact={false} />
            </Suspense>
          </LazySection>
        </EditorialSection>

        <EditorialSection index="05" label="CALENDAR" jaLabel="カレンダー"
          description="Events, holidays and birthdays coming up. Tap any day to see what is on."
          jaDescription="これからの予定・祝日・誕生日がわかります。日付をタップすると詳しい内容が見られます。">
          <LazySection minHeight={620}>
            <Suspense fallback={<WidgetFallback minHeight={620} />}>
              <CalendarWidget />
            </Suspense>
          </LazySection>
        </EditorialSection>

        <EditorialSection index="06" label="SCHEDULE" jaLabel="スケジュール"
          description="The normal class timetable for the week."
          jaDescription="今週のふだんの時間割です。">
          <LazySection minHeight={420}>
            <Suspense fallback={<WidgetFallback minHeight={420} />}>
              <ScheduleWidget isAdmin={canManage} />
            </Suspense>
          </LazySection>
        </EditorialSection>

        <EditorialSection index="07" label="LOST AND FOUND" jaLabel="落とし物"
          description="Lost something? Add it here so people can look out for it. Found something? Check whether anyone is missing it."
          jaDescription="何かなくしましたか？ここに追加すると、みんなが気にかけてくれます。何かを見つけたら、探している人がいないか確認してください。">
          <LazySection minHeight={420}>
            <Suspense fallback={<WidgetFallback minHeight={420} />}>
              <MissingItemsWidget members={members} />
            </Suspense>
          </LazySection>
        </EditorialSection>

        <EditorialSection index="08" label="LUNCH MENU" jaLabel="ランチメニュー"
          description="What is for snack and lunch on each day this week."
          jaDescription="今週の各曜日のおやつとランチの内容です。">
          <LazySection minHeight={420}>
            <Suspense fallback={<WidgetFallback minHeight={420} />}>
              <LunchMenuWidget isAdmin={canManage} />
            </Suspense>
          </LazySection>
        </EditorialSection>

        <EditorialSection index="09" label="NEWS" jaLabel="ニュース"
          description="Longer stories and updates from around the school."
          jaDescription="学校のいろいろな出来事についての、少し長めの記事です。">
          <LazySection minHeight={480}>
            <Suspense fallback={<WidgetFallback minHeight={480} />}>
              <NewsWidget members={members} isAdmin={canManage} />
            </Suspense>
          </LazySection>
        </EditorialSection>

        <EditorialSection index="10" label="MEMBERS" jaLabel="メンバー"
          description="Everyone in the community, and the job or role each person has right now."
          jaDescription="コミュニティの全員と、それぞれが今担当している係や役割がわかります。">
          <LazySection minHeight={560}>
            <Suspense fallback={<WidgetFallback minHeight={560} />}>
              <MembersWidget isAdmin={canManage} canChangeRoles={isSummerOrBenjamin || isMinutesTaker} />
            </Suspense>
          </LazySection>
        </EditorialSection>

        </div>

        <PageFooter />
      </main>
      <IdleMount timeout={1800}>
        <Suspense fallback={null}>
          <JobReminder />
          <MabisAIAssistant />
          <FeedbackWidget />
        </Suspense>
      </IdleMount>
    </div>);
}
