// solid/components/MeetingNotesEditor.jsx
import { createSignal, createEffect, onCleanup, lazy, Suspense, Show } from "solid-js";
import { useQuery, useMutation, useQueryClient } from "@tanstack/solid-query";
import { base44 } from "@/api/base44Client";

const DocsEditor = lazy(() => import("~/components/DocsEditor"));

/*
 * Autosaving meeting notes — 1:1 port of src/components/MeetingNotesEditor.jsx.
 *
 * The record id lives in a plain variable, not a signal: it is written during a
 * create→update transition and must never re-trigger a render, because that
 * would remount the editor mid-typing. React used a ref for the same reason.
 */
export default function MeetingNotesEditor(props) {
  const queryClient = useQueryClient();
  const [savedFlash, setSavedFlash] = createSignal(false);
  let saveTimer;
  let flashTimer;
  let recordId = null;
  let pendingHtml = null;

  const topicsQuery = useQuery(() => ({
    queryKey: ["topics", props.weekLabel],
    queryFn: () => base44.entities.DiscussionTopic.filter(
      { week_label: props.weekLabel }, "-created_date", 100,
    ),
  }));

  const allTopics = () => topicsQuery.data || [];
  const notesRecord = () => allTopics().find(
    (t) => t.week_label === props.weekLabel && t.is_jobs_topic === true && t.title === "__meeting_notes__",
  );

  createEffect(() => {
    const record = notesRecord();
    if (record) recordId = record.id;
  });

  const saveMutation = useMutation(() => ({
    mutationFn: async (html) => {
      if (recordId) {
        return base44.entities.DiscussionTopic.update(recordId, { description: html });
      }
      const created = await base44.entities.DiscussionTopic.create({
        title: "__meeting_notes__",
        submitted_by: "system",
        week_label: props.weekLabel,
        is_jobs_topic: true,
        description: html,
      });
      recordId = created.id;
      return created;
    },
    onSuccess: () => {
      setSavedFlash(true);
      clearTimeout(flashTimer);
      flashTimer = setTimeout(() => setSavedFlash(false), 2200);
      queryClient.invalidateQueries({ queryKey: ["topics"] });
    },
  }));

  const flushPending = () => {
    if (pendingHtml === null) return;
    clearTimeout(saveTimer);
    const html = pendingHtml;
    pendingHtml = null;
    saveMutation.mutate(html);
  };

  const handleChange = (html) => {
    pendingHtml = html;
    clearTimeout(saveTimer);
    saveTimer = setTimeout(flushPending, 600);
  };

  const flushOnExit = () => {
    if (document.visibilityState === "hidden") flushPending();
  };
  document.addEventListener("visibilitychange", flushOnExit);
  window.addEventListener("pagehide", flushPending);

  onCleanup(() => {
    document.removeEventListener("visibilitychange", flushOnExit);
    window.removeEventListener("pagehide", flushPending);
    clearTimeout(flashTimer);
    flushPending();
  });

  return (
    <Show
      when={!topicsQuery.isLoading}
      fallback={<div class="border border-border bg-card px-4 py-6 text-sm text-muted-foreground">Loading notes…</div>}
    >
      {/* One normal document, not the old block/column editor. `keyed` keeps
          each week isolated because Quill seeds initialHtml only on mount. */}
      <Suspense fallback={<div class="min-h-[360px] border border-border bg-card" aria-label="Meeting notes editor loading" />}>
        <Show when={props.weekLabel} keyed>
          {() => (
            <DocsEditor
              title="Meeting Notes"
              initialHtml={notesRecord()?.description || ""}
              onChange={handleChange}
              onSave={flushPending}
              saving={saveMutation.isPending}
              saved={savedFlash()}
              minHeight="360px"
              stickyTop="0px"
              placeholder="Write meeting notes like a normal document…"
            />
          )}
        </Show>
      </Suspense>
    </Show>
  );
}

// src/components/MeetingNotesEditor.jsx
import React, { useEffect, useRef, useState } from "react";
import { base44 } from "@/api/base44Client";
import { useQuery, useMutation } from "@tanstack/react-query";
import BlockNotesEditor from "@/components/notes/BlockNotesEditor";

export default function MeetingNotesEditor({ weekLabel }) {
  const [savedFlash, setSavedFlash] = useState(false);
  const saveTimer = useRef(null);
  const flashTimer = useRef(null);
  // The record id lives in a ref so a create → update transition never
  // remounts the editor mid-typing.
  const recordIdRef = useRef(null);

  const { data: allTopics = [], isLoading } = useQuery({
    queryKey: ["topics", weekLabel, "meeting-notes"],
    queryFn: () => base44.entities.DiscussionTopic.filter({
      week_label: weekLabel,
      title: "__meeting_notes__",
    }),
    enabled: Boolean(weekLabel),
  });

  const notesRecord = allTopics.find(t => t.is_jobs_topic === true && t.title === "__meeting_notes__");
  useEffect(() => { if (notesRecord) recordIdRef.current = notesRecord.id; }, [notesRecord]);

  const saveMutation = useMutation({
    mutationFn: async (html) => {
      if (recordIdRef.current) {
        return base44.entities.DiscussionTopic.update(recordIdRef.current, { description: html });
      }
      const created = await base44.entities.DiscussionTopic.create({
        title: "__meeting_notes__",
        submitted_by: "system",
        week_label: weekLabel,
        is_jobs_topic: true,
        description: html,
      });
      recordIdRef.current = created.id;
      return created;
    },
    onSuccess: () => {
      setSavedFlash(true);
      clearTimeout(flashTimer.current);
      flashTimer.current = setTimeout(() => setSavedFlash(false), 2200);
    },
  });

  const handleChange = (html) => {
    clearTimeout(saveTimer.current);
    saveTimer.current = setTimeout(() => saveMutation.mutate(html), 600);
  };

  useEffect(() => () => { clearTimeout(saveTimer.current); clearTimeout(flashTimer.current); }, []);

  const status = saveMutation.isPending ? "SAVING…" : savedFlash ? "✓ SAVED" : "AUTOSAVE ON";

  if (isLoading) {
    return <div className="border border-border bg-card px-4 py-6 text-sm text-muted-foreground">Loading notes…</div>;
  }

  // Keyed on the week only — refetches never remount the editor mid-typing.
  return (
    <BlockNotesEditor
      key={weekLabel}
      initialHtml={notesRecord?.description || ""}
      onChange={handleChange}
      status={status}
    />
  );
}
