// solid/components/MotionPreference.jsx
import { createSignal, createEffect, onMount, onCleanup } from "solid-js";
import { animationsDisabled, applyAnimationPreference, MOTION_EVENT } from "@/lib/motion-preference";
import { applyLowPowerMode, detectLowPowerDevice, monitorFrameBudget } from "@/lib/performance-tier";

/*
 * Motion preference — port of src/components/MotionPreference.jsx.
 *
 * React wrapped its children in framer's <MotionConfig> and toggled
 * MotionGlobalConfig.skipAnimations. Neither exists here, and neither is
 * needed: this port has no JS animation runtime at all. Every animation is a
 * CSS keyframe or transition, and solid-motion.css switches the whole lot off
 * under `html.animations-disabled` — the class that applyAnimationPreference
 * writes. So the preference is enforced by the same call, one layer lower.
 *
 * The OS-level reduced-motion preference that MotionConfig honoured is picked
 * up directly by the prefers-reduced-motion media queries in the stylesheets.
 */
export default function MotionPreference(props) {
  const [disabled, setDisabled] = createSignal(animationsDisabled());
  const [lowPower, setLowPower] = createSignal(detectLowPowerDevice());

  createEffect(() => applyLowPowerMode(lowPower()));

  onMount(() => {
    const stop = monitorFrameBudget(() => setLowPower(true));
    onCleanup(() => stop?.());
  });

  // A performance tier may simplify expensive glass/cursor work, but it must
  // never override the user's animation setting.
  createEffect(() => applyAnimationPreference(disabled()));

  onMount(() => {
    const update = (event) => setDisabled(event.detail);
    window.addEventListener(MOTION_EVENT, update);
    onCleanup(() => window.removeEventListener(MOTION_EVENT, update));
  });

  return <>{props.children}</>;
}

// src/components/MotionPreference.jsx
import { useEffect, useState } from "react";
import { MotionConfig, MotionGlobalConfig } from "framer-motion";
import { animationsDisabled, applyAnimationPreference, MOTION_EVENT } from "@/lib/motion-preference";
import { applyLowPowerMode, detectLowPowerDevice, monitorFrameBudget } from "@/lib/performance-tier";

/* Motion off = everything simply exists: framer skips every animation
   (including ones with their own explicit transition, like the section
   reveals), and CSS keyframes/transitions are stopped alongside it. */
if (typeof window !== "undefined") {
  MotionGlobalConfig.skipAnimations = animationsDisabled();
}

export default function MotionPreference({ children }) {
  const [disabled, setDisabled] = useState(animationsDisabled);
  const [lowPower, setLowPower] = useState(detectLowPowerDevice);
  // A performance tier may simplify expensive glass/cursor work, but it must
  // never override the user's animation setting. MotionConfig still honors
  // the operating system's reduced-motion accessibility preference.
  const effectiveDisabled = disabled;

  useEffect(() => {
    applyLowPowerMode(lowPower);
  }, [lowPower]);

  useEffect(() => monitorFrameBudget(() => setLowPower(true)), []);

  useEffect(() => {
    MotionGlobalConfig.skipAnimations = effectiveDisabled;
    applyAnimationPreference(disabled);
    const update = (event) => setDisabled(event.detail);
    window.addEventListener(MOTION_EVENT, update);
    return () => window.removeEventListener(MOTION_EVENT, update);
  }, [disabled, effectiveDisabled]);

  return (
    <MotionConfig
      key={effectiveDisabled ? "static" : "motion"}
      reducedMotion={effectiveDisabled ? "always" : "user"}
      transition={effectiveDisabled ? { duration: 0, delay: 0 } : undefined}
    >
      {children}
    </MotionConfig>
  );
}
